[package]
name = "hello-tikv-rust"
version = "0.1.0"
authors = ["Terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"

[dependencies]
tikv-client = { git = "https://github.com/tikv/client-rust.git" }
