[package]
authors = ["Terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "hello-tikv-rust"
version = "0.1.0"

[dependencies]
tikv-client = {git = "https://github.com/tikv/client-rust.git"}
tokio = {version = "0.2", features = ["sync", "macros"]}
